MODEL:
  PRETRAIN_PATH: './modeling/densenet121-fbdb23505.pth'


INPUT:
  SIZE_TRAIN: [288, 288]
  SIZE_TEST: [256, 256]
  PROB: 0.5 # random horizontal flip
  PADDING: 10
  COLORJITTER: False  # for model ensemble
  
DATASETS:
  NAMES: ('VR_sy_test')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 2
  SOFT_MARGIN: False # for model ensemble

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 80
  BASE_LR: 0.01 #0.00035
  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
#  IMS_PER_BATCH: 64 
  IMS_PER_BATCH: 32

  STEPS: [30, 60, 100]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 10
  LOG_PERIOD: 40
  EVAL_PERIOD: 10

TEST:
  IMS_PER_BATCH: 256
  WEIGHT: "path"

OUTPUT_DIR: "./CHECKPOINTS/VR_sy"


